x86: Force __x86_indirect_thunk_reg for function call via GOT
For x86 targets, when -fno-plt is used, external functions are called
via GOT slot, in 64-bit mode:

	[bnd] call/jmp *foo@GOTPCREL(%rip)

and in 32-bit mode:

	[bnd] call/jmp *foo@GOT[(%reg)]

With -mindirect-branch=, they are converted to, in 64-bit mode:

	pushq          foo@GOTPCREL(%rip)
	[bnd] jmp      __x86_indirect_thunk[_bnd]

and in 32-bit mode:

	pushl          foo@GOT[(%reg)]
	[bnd] jmp      __x86_indirect_thunk[_bnd]

which were incompatible with CFI.

This patch extends x32 call via GOT patterns to LP64 and adds patterns
for call via GOT with R11 as scratch register.  We generate:

	movq           foo@GOTPCREL(%rip), %r11
	[bnd] call/jmp __x86_indirect_thunk_[bnd_]r11

In this way, we can use the newly proposed R_X86_64_THUNK_GOTPCRELX
relocation:

https://groups.google.com/forum/#!topic/x86-64-abi/eED5lzn3_Mg

	movq           foo@OTPCREL_THUNK(%rip), %r11
	[bnd] call/jmp __x86_indirect_thunk_[bnd_]r11

to load GOT slot into R11.  If foo is defined locally, linker can can
convert

	movq           foo@GOTPCREL_THUNK(%rip), %reg
	call/jmp       __x86_indirect_thunk_reg

to

	call/jmp       foo
	nop            0L(%rax)

In 32-bit mode, since all caller-saved registers, EAX, EDX and ECX, may
used to function parameters, there is no scratch register available.  For
-fno-plt -fno-pic -mindirect-branch=, we expand external function call
to:

	movl           foo@GOT, %reg
	[bnd] call/jmp *%reg

so that it can be converted to

	movl           foo@GOT, %reg
	[bnd] call/jmp __x86_indirect_thunk_[bnd_]reg

in ix86_output_indirect_branch.  Since this is performed during RTL
expansion, other instructions may be inserted between movl and call/jmp.
Linker optimization isn't always possible.

NB: I don't find a way to make register allocator to find a scratch
register used in call pattern so that I can use it in 32-bit mode:

remainderq.c: In function ‘remainderq’:
remainderq.c:67:1: error: unable to generate reloads for:
 }
 ^
(call_insn 124 382 125 9 (parallel [
            (call (mem:QI (mem/u/c:SI (plus:SI (reg:SI 87)
                            (const:SI (unspec:SI [
                                        (symbol_ref:SI ("__addtf3") [flags 0x41])
                                    ] UNSPEC_GOT))) [0  S4 A8]) [0  S1 A8])
                (const_int 48 [0x30]))
            (set (reg/f:SI 7 sp)
                (plus:SI (reg/f:SI 7 sp)
                    (const_int 4 [0x4])))
            (use (reg:SI 149))
        ]) "/export/gnu/import/git/sources/gcc/libquadmath/math/remainderq.c":48 692 {*call_pop_GOT_thunk_32}
     (expr_list:REG_DEAD (reg:SI 149)
        (expr_list:REG_CALL_DECL (symbol_ref:SI ("__addtf3") [flags 0x41])
            (expr_list:REG_ARGS_SIZE (const_int 44 [0x2c])
                (expr_list:REG_EH_REGION (const_int -2147483648 [0xffffffff80000000])
                    (nil)))))
    (expr_list (use (mem:TF (plus:SI (reg/f:SI 7 sp)
                    (scratch:SI)) [0  S16 A8]))
        (nil)))
during RTL pass: reload
remainderq.c:67:1: internal compiler error: in curr_insn_transform, at lra-constraints.c:3903

gcc/

	PR target/83970
	* config/i386/constraints.md (Bs): Allow GOT_memory_operand
	for TARGET_LP64 with indirect branch conversion.
	(Bw): Likewise.
	* config/i386/i386-protos.h (ix86_output_call_insn): Add an
	argument for scratch register.
	* config/i386/i386.c (ix86_expand_call): In 64-bit mode, for
	-fno-plt with -mindirect-branch=, call external function via
	GOT with a scratch register.
	(ix86_nopic_noplt_attribute_p): Likewise.
	(ix86_output_indirect_branch): Add an argument for scratch
	register.  Make function call via GOT with scratch register.
	(ix86_output_indirect_jmp): Pass NULL_RTX as scratch register
	to ix86_output_indirect_branch.
	(ix86_output_call_insn): Add an argument for scratch register.
	Pass scratch register to ix86_output_indirect_branch.
	* config/i386/i386.md (*call): Pass NULL_RTX as scratch register
	to ix86_output_call_insn.
	(*sibcall_GOT_32): Likewise.
	(*sibcall): Likewise.
	(*sibcall_memory): Likewise.
	(*sibcall_pop): Likewise.
	(*sibcall_pop_memory): Likewise.
	(*call_value): Likewise.
	(*sibcall_value_GOT_32): Likewise.
	(*sibcall_value): Likewise.
	(*sibcall_value_memory): Likewise.
	(*call_value_pop): Likewise.
	(*sibcall_value_pop): Likewise.
	(*sibcall_value_pop_memory): Likewise.
	(*call_got_x32): Renamed to ...
	(*call_got): This.  Support TARGET_64BIT.
	(*call_value_got_x32): Renamed to ...
	(*call_value_got): This.  Support TARGET_64BIT.
	(*call_got_thunk): New pattern for call via GOT with R11 as
	scratch register.
	(*call_value_got_thunk): Likewise.

gcc/testsuite/

	PR target/83970
	* gcc.target/i386/indirect-thunk-5.c: Updated.
	* gcc.target/i386/indirect-thunk-6.c: Likewise.
	* gcc.target/i386/indirect-thunk-bnd-3.c: Likewise.
	* gcc.target/i386/indirect-thunk-bnd-4.c: Likewise.
	* gcc.target/i386/indirect-thunk-extern-5.c: Likewise.
	* gcc.target/i386/indirect-thunk-extern-6.c: Likewise.
	* gcc.target/i386/indirect-thunk-inline-5.c: Likewise.
	* gcc.target/i386/indirect-thunk-inline-6.c: Likewise.
	* gcc.target/i386/indirect-thunk-13.c: New test.
	* gcc.target/i386/indirect-thunk-14.c: Likewise.
	* gcc.target/i386/indirect-thunk-bnd-5.c: Likewise.
	* gcc.target/i386/indirect-thunk-bnd-6.c: Likewise.
	* gcc.target/i386/indirect-thunk-extern-11.c: Likewise.
	* gcc.target/i386/indirect-thunk-extern-12.c: Likewise.
	* gcc.target/i386/indirect-thunk-inline-8.c: Likewise.
	* gcc.target/i386/indirect-thunk-inline-9.c: Likewise.